"""Add all models and user_communities

Revision ID: 496ffcc4857b
Revises: 85e2ed80844d
Create Date: 2025-08-24 17:34:00.871579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496ffcc4857b'
down_revision = '85e2ed80844d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_communities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'community_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_communities')
    # ### end Alembic commands ###
